### ISSUE TITLE
Reading output data

### ISSUE THREAD

**Issue by tzuifurther** [alib022/GEDicomReader#2]
Dear all
     I have the question for reading output file. Does it has some guide?

**Comment by alib022** [comment]
Hi
Thanks for using this old code!
The vtk output can be used by paraview app. However, given I haven't touched this code for so many years I don't even know if it can convert new 4D Flow Dicom files anymore.

**Comment by tzuifurther** [comment]
Thank you

**Comment by tzuifurther** [comment]
I have DICOM which have same version, and it can run output file. Maybe it could run currently
